Korean Translation Core~Cycle 2
zzorba/marvelsdb-json-data pull request #180
Opened 2022-02-17 15:07 UTC by scappy64

Starting with core~cycle 2, gradually catching up with global players.

2022-02-18 03:27 UTC, elkeinkrad requested changes
Here are some json format error.

2022-02-18 03:27 UTC, elkeinkrad commented on translations/ko/pack/core_encounter.json
> +		"text": "<b>공개될 때</b>: Rhino에게 강인함 상태 카드를 줍니다. Rhino에게 이미 강인함 상태 카드가 있다면, 이 카드는 쇄도를 얻습니다.
json format issue
```suggestion
		"text": "<b>공개될 때</b>: Rhino에게 강인함 상태 카드를 줍니다. Rhino에게 이미 강인함 상태 카드가 있다면, 이 카드는 쇄도를 얻습니다."
```

2022-02-18 03:27 UTC, elkeinkrad commented on translations/ko/pack/core_encounter.json
> +		"name": "비밀스러운 회동,
json format issue

```suggestion
		"name": "비밀스러운 회동",
```

2022-02-18 03:27 UTC, elkeinkrad commented on translations/ko/pack/core_encounter.json
> +		"attack_text": "<b>강제 반응</b>: Klaw가 공격하여 캐릭터에게 피해를 입힌 후, 그 캐릭터를 기절시킵니다.
json format issue
```suggestion
		"attack_text": "<b>강제 반응</b>: Klaw가 공격하여 캐릭터에게 피해를 입힌 후, 그 캐릭터를 기절시킵니다.",
```

2022-02-18 03:27 UTC, elkeinkrad commented on translations/ko/pack/core_encounter.json
> +		"name": "음파 변환기,
json format issue
```suggestion
		"name": "음파 변환기",
```

2022-02-18 03:32 UTC, elkeinkrad commented
Note to maintainer: This PR is written as unicode instead of ASCII. I think this is ok. However, if any problem occurs (unlike arkhamDB), the reason may be encoding issue.

2022-02-21 03:44 UTC, elkeinkrad requested changes

2022-02-21 03:44 UTC, elkeinkrad commented on translations/ko/pack/gob_encounter.json
> +		"attack_text": "<b>강제 반응</b>: 빌런이 당신을 공격한 후, 호박 폭탄을 버리고 간접 피해 2점을 입습니다."
```suggestion
		"attack_text": "<b>강제 반응</b>: 빌런이 당신을 공격한 후, 호박 폭탄을 버리고 간접 피해 2점을 입습니다.",
```

2022-03-03 22:35 UTC, Kamalisk commented
unicode should be fine. looks like there is some invalid json somewhere though.

2022-03-04 00:17 UTC, scappy64 commented
> unicode should be fine. looks like there is some invalid json somewhere though.

Fixed!! Thank you.

2022-03-17 06:03 UTC, scappy64 commented
Due to Korean Copyright, I deleted all encounter card translation.

2022-06-26 21:32 UTC, merged